# Generated by Django 5.0.6 on 2024-09-04 15:43

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DetectedMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message_id", models.BigIntegerField(unique=True)),
                ("chat_id", models.BigIntegerField()),
                ("chat_name", models.CharField(blank=True, max_length=255, null=True)),
                ("sender_id", models.BigIntegerField()),
                (
                    "sender_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "sender_username",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("text", models.TextField()),
                ("date", models.DateTimeField()),
                ("message_link", models.URLField(blank=True, null=True)),
            ],
        ),
    ]
