# Generated by Django 5.0.6 on 2024-09-09 05:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("telegramapi", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TelegramUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.BigIntegerField(unique=True)),
                ("username", models.CharField(blank=True, max_length=150, null=True)),
                ("first_name", models.CharField(max_length=150)),
                ("last_name", models.CharField(blank=True, max_length=150, null=True)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("photo", models.FileField(upload_to=None)),
                ("is_bot", models.BooleanField(default=False)),
            ],
        ),
    ]
