# Generated by Django 5.0.6 on 2025-02-22 10:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("telegramapi", "0004_alter_telegramuser_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="detectedmessage",
            name="detected_by",
            field=models.CharField(
                choices=[("AI", "AI"), ("Pattern", "Pattern")],
                default="Pattern",
                max_length=50,
            ),
        ),
    ]
