# Generated by Django 5.0.6 on 2025-02-22 10:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("telegramapi", "0005_detectedmessage_detected_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="detectedmessage",
            name="message_id",
            field=models.BigIntegerField(),
        ),
    ]
